config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pins

  root 'pins#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy]

  def index
    @pins = Pin.all
  end
    
  def new
    @pin = current_user.pins.build
  end
    
  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created!'
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated!'
    else
      render 'edit'
    end    
  end
  
  
  def destroy
    @pin.destroy
    redirect_to root_path
  end
  
  private 

  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end

  def find_pin
    @pin = Pin.find(params[:id])   
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-toggleable-md.navbar-light.bg-faded
  %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  %a.navbar-brand{:href => root_path} Pin Board
  #navbarSupportedContent.collapse.navbar-collapse
    - if user_signed_in?
      %ul.navbar-nav.mr-auto
        %li.nav-item.active
          %a.nav-link{:href => new_pin_path}
            New Post
        %li.nav-item
          %a.nav-link{:href => edit_user_registration_path} Account
        %li.nav-item
          .nav-link= link_to 'Sign Out', destroy_user_session_path, method: :delete
    - else
      %ul.navbar-nav.mr-auto
        %li.nav-item.active
          %a.nav-link{:href => new_user_session_path}
            Sign in
        %li.nav-item
          %a.nav-link{:href => new_user_registration_path} Sign Up

    %form.form-inline.my-2.my-lg-0
      %input.form-control.mr-sm-2{:placeholder => "Search", :type => "text"}/
      %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title PinterestApp
    = csrf_meta_tags 
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 
  %body
    = render 'layouts/navigation'
    - flash.each do |name, msg|
      = content_tag :div, msg, class: 'alert alert-info'

    .container  
      = yield
  

app/views/pins/_form.html.haml
= simple_form_for @pin do |f|
  = f.input :title, error: 'Title is mandatory, please specify one'
  = f.input :description, as: :text, 
                          error: 'Please add a little info',
                          input_html: { rows: 30 }
  = f.button :submit, 'Update post', :class => 'btn btn-primary'
  .btn.btn-secondary
    = link_to 'Cancel', pin_path 
 

app/views/pins/edit.html.haml
.row
  .col-lg-8.offset-lg-2
    %h1 Edit pin
    = simple_form_for @pin do |f|
      = image_tag @pin.image.url(:thumb)
      = f.input :image, label: false, input_html: { class: 'form-control' }
      = f.input :title, error: 'Title is mandatory, please specify one'
      = f.input :description, as: :text, 
                              error: 'Please add a little info',
                              input_html: { rows: 10 }
      = f.button :submit, 'Update post', :class => 'btn btn-primary'
      .btn.btn-secondary
        = link_to 'Cancel', pin_path 

app/views/pins/index.html.haml
.jumbotron
  - @pins.each do |pin|
    = link_to (image_tag pin.image.url(:medium)), pin
    %h2= link_to(pin.title, pin)

app/views/pins/new.html.haml
%h1 Create a new pin

= simple_form_for @pin do |f|
  = f.input :title, error: 'Title is mandatory, please specify one'
  = f.input :image, as: :file, label: false
  = f.input :description, as: :text, 
                          error: 'Please add a little info',
                          input_html: { rows: 30 }
  = f.button :submit, 'Create Post', :class => 'btn btn-primary'
  .btn.btn-secondary
    = link_to 'Cancel', root_path 
  

app/views/pins/show.html.haml
%h1= @pin.title
= link_to (image_tag @pin.image.url(:medium)), @pin
%blockquote.blockquote= @pin.description

%footer.blockquote-footer.float-right= @pin.user.email

= link_to 'Back', root_path
= link_to 'Edit', edit_pin_path
= link_to 'Delete', pin_path, method: :delete, data: {confirm: 'Are you sure?'}